### ISSUE TITLE
add server configuration manual for php builtin webserver

### ISSUE THREAD

**Issue by Flyingmana** [UnionOfRAD/manual#28]
http://lithify.me/docs/manual/configuration/servers

i would like to have an manual for the builtin webserver of php: http://php.net/manual/en/features.commandline.webserver.php

**Comment by davidpersson** [comment]
I've added support for builtin webserver to the framework distro:
https://github.com/UnionOfRAD/framework/commit/6d8d4c6ec62729b7aa56f506f19fe32fac80efaa

And the installation page has been rewritten to take advantage of it in order to simplify setup. It is assumed that people nowadays are on 5.4 for their dev environment at a minimum. Other webservers are still supported for installation via the webservers page.

https://github.com/UnionOfRAD/manual/blob/dev/en/installation/README.md
