### ISSUE TITLE
links from Google lead to empty pages

### ISSUE THREAD

**Issue by alexanderhaensch** [UnionOfRAD/manual#96]
many links from google end up in an empty page:
http://li3.me/docs/book/manual/1.x/views/views

There could be a redirect to 
http://li3.me/docs/book/manual/1.x/views

**Comment by davidpersson** [comment]
We've changed the documentation section of website recently. I'm currently in the process of handling errors that come from faulty links in manual, and API docs which are now revealed since we also changed the URL structure.

There are already multiple redirect routes in place which should handle this.

**Comment by davidpersson** [comment]
I think I fixed most of these. We now have to wait until Google updates its index.
https://github.com/UnionOfRAD/lithium/commit/93bda3b92fe2edf22e9b0dd1e66c1caa3fdc3c51
https://github.com/UnionOfRAD/lithium/commit/933ba3c1fc423a0ba968f523ea083e4add4b11e7
https://github.com/UnionOfRAD/lithium/commit/27155556c385d687ae55ba82c23631e3b4ebe692
https://github.com/UnionOfRAD/lithium/commit/6eb7ea3624f1ad9c6c5b20d0ce7897b4884c4e3c
